version: '3.6'
services:

  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.toml:/etc/traefik/traefik.toml:ro
      # - ./acme.json:/acme.json
    networks:
      - mynetwork

  postgres:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=Welcome1!
    ports: 
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    labels:
      - "traefik.enable=false"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "postgresql@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "Welcome1!"
    ports: 
      - "16543:80"
    depends_on: 
      - postgres
    volumes:
      - ./pgadmin-conf:/mnt/data:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=insecure"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.docker.jobjects.org`)"
      - "traefik.docker.network=mynetwork"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true